import { Composer } from "grammy";
import type { Ctx } from "../bot.js";
import { inlineButton, inlineKeyboard, requireOwner } from "../toolkit/index.js";
import { allTeams, log, readTournament, teamPlayers, writeTournament, type Match, type Team } from "../tournament-store.js";
const composer = new Composer<Ctx>();
const input = { force_reply: true, input_field_placeholder: "Type your answer" } as const;
const actor = (ctx: Ctx) => String(ctx.from?.id ?? ctx.chat?.id ?? "");
async function admin(ctx: Ctx) { return requireOwner(ctx as never); }
const panelKeys = () => inlineKeyboard([[inlineButton("Pending rosters", "admin:pending"), inlineButton("Conflicts", "admin:conflicts")], [inlineButton("Schedule match", "admin:schedule"), inlineButton("Matches", "admin:matches")]]);
async function notify(ctx: Ctx, team: Team, text: string) { try { await ctx.api.sendMessage(team.captainTelegramId, text); } catch { /* Captains can always see status in the public table. */ } }
composer.command("admin", async (ctx) => { if (!(await admin(ctx))) return; await ctx.reply("Admin panel. Choose an action.", { reply_markup: panelKeys() }); });
composer.callbackQuery("admin:panel", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await admin(ctx))) return; await ctx.reply("Admin panel. Choose an action.", { reply_markup: panelKeys() }); });
composer.callbackQuery("admin:pending", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await admin(ctx))) return; const data = await readTournament(ctx); const pending = allTeams(data).filter((team) => team.status === "PENDING"); if (!pending.length) return void await ctx.reply("No pending rosters."); await ctx.reply("Pending rosters:", { reply_markup: inlineKeyboard(pending.map((team) => [inlineButton(team.name, `admin:team:${team.id}`)])) }); });
composer.callbackQuery(/^admin:team:(t\d+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await admin(ctx))) return; const data = await readTournament(ctx); const team = data.teams[ctx.match?.[1] ?? ""]; if (!team) return void await ctx.reply("That roster is no longer available."); ctx.session.adminTeamId = team.id; const roster = teamPlayers(data, team).map((player, index) => `${index + 1}. ${player.fullName} — ${player.inGameId}`).join("\n"); await ctx.reply(`${team.name}\n${roster}`, { reply_markup: inlineKeyboard([[inlineButton("Approve", `admin:approve:${team.id}`), inlineButton("Reject", `admin:reject:${team.id}`)], [inlineButton("Edit roster", `admin:edit:${team.id}`)]] ) }); });
composer.callbackQuery(/^admin:approve:(t\d+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await admin(ctx))) return; const data = await readTournament(ctx); const team = data.teams[ctx.match?.[1] ?? ""]; if (!team || team.status === "CONFLICTED") return void await ctx.reply("Resolve roster conflicts before approval."); team.status = "APPROVED"; log(data, actor(ctx), "approved roster", team.id); await writeTournament(ctx, data); await notify(ctx, team, "Your roster is approved."); await ctx.reply(`${team.name} is approved.`); });
composer.callbackQuery(/^admin:reject:(t\d+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await admin(ctx))) return; ctx.session.adminTeamId = ctx.match?.[1]; ctx.session.flow = "admin_reject"; await ctx.reply("Enter the rejection reason.", { reply_markup: input }); });
composer.callbackQuery(/^admin:edit:(t\d+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await admin(ctx))) return; const data = await readTournament(ctx); const team = data.teams[ctx.match?.[1] ?? ""]; if (!team) return void await ctx.reply("That roster is no longer available."); ctx.session.adminTeamId = team.id; await ctx.reply("Choose a player to edit.", { reply_markup: inlineKeyboard(team.playerIds.map((_, index) => [inlineButton(`Edit player ${index + 1}`, `admin:player:${index}`)])) }); });
composer.callbackQuery(/^admin:player:(\d+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await admin(ctx))) return; ctx.session.editIndex = Number(ctx.match?.[1]); ctx.session.flow = "admin_edit_player"; await ctx.reply("Send: full name | in-game ID | Telegram username. Use - for no username.", { reply_markup: input }); });
composer.callbackQuery("admin:conflicts", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await admin(ctx))) return; const data = await readTournament(ctx); const list = data.conflictIds.map((id) => data.conflicts[id]).filter((conflict) => conflict?.status === "OPEN"); if (!list.length) return void await ctx.reply("No open conflicts."); await ctx.reply("Open conflicts:", { reply_markup: inlineKeyboard(list.map((conflict) => [inlineButton(`${conflict.inGameId} (${conflict.id})`, `admin:conflict:${conflict.id}`)])) }); });
composer.callbackQuery(/^admin:conflict:(c\d+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await admin(ctx))) return; const data = await readTournament(ctx); const conflict = data.conflicts[ctx.match?.[1] ?? ""]; if (!conflict || conflict.status !== "OPEN") return void await ctx.reply("That conflict is already resolved."); const choices = conflict.teamIds.map((id) => data.teams[id]).filter(Boolean); await ctx.reply(`Duplicate in-game ID: ${conflict.inGameId}. Choose the roster that keeps it, or reject all affected rosters.`, { reply_markup: inlineKeyboard([...choices.map((team) => [inlineButton(`Keep ${team.name}`, `admin:keep:${conflict.id}:${team.id}`)]), [inlineButton("Reject affected", `admin:rejectconf:${conflict.id}`)], [inlineButton("Merge into first roster", `admin:merge:${conflict.id}`)]]) }); });
async function resolve(ctx: Ctx, conflictId: string, keepId?: string, rejectAll = false) { const data = await readTournament(ctx); const conflict = data.conflicts[conflictId]; if (!conflict || conflict.status !== "OPEN") return void await ctx.reply("That conflict is already resolved."); for (const teamId of conflict.teamIds) { const team = data.teams[teamId]; if (!team) continue; if (rejectAll || (keepId && teamId !== keepId)) { team.status = "REJECTED"; await notify(ctx, team, "Your roster was rejected during duplicate-ID resolution. Contact the organizer to submit a corrected roster."); } else { team.status = "PENDING"; } }
  conflict.status = "RESOLVED"; log(data, actor(ctx), keepId ? "resolved conflict" : "rejected conflict", conflict.id); await writeTournament(ctx, data); await ctx.reply("Conflict resolved. The retained roster is pending approval."); }
composer.callbackQuery(/^admin:keep:(c\d+):(t\d+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (await admin(ctx)) await resolve(ctx, ctx.match?.[1] ?? "", ctx.match?.[2]); });
composer.callbackQuery(/^admin:rejectconf:(c\d+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (await admin(ctx)) await resolve(ctx, ctx.match?.[1] ?? "", undefined, true); });
composer.callbackQuery(/^admin:merge:(c\d+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await admin(ctx))) return; const data = await readTournament(ctx); const conflict = data.conflicts[ctx.match?.[1] ?? ""]; await resolve(ctx, conflict?.id ?? "", conflict?.teamIds[0]); });
composer.callbackQuery("admin:schedule", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await admin(ctx))) return; const data = await readTournament(ctx); const approved = allTeams(data).filter((team) => team.status === "APPROVED"); if (approved.length < 2) return void await ctx.reply("Approve at least two rosters before scheduling a match."); await ctx.reply("Choose the first team.", { reply_markup: inlineKeyboard(approved.map((team) => [inlineButton(team.name, `admin:schedulea:${team.id}`)])) }); });
composer.callbackQuery(/^admin:schedulea:(t\d+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await admin(ctx))) return; ctx.session.adminTeamId = ctx.match?.[1]; const data = await readTournament(ctx); const choices = allTeams(data).filter((team) => team.status === "APPROVED" && team.id !== ctx.session.adminTeamId); await ctx.reply("Choose the second team.", { reply_markup: inlineKeyboard(choices.map((team) => [inlineButton(team.name, `admin:scheduleb:${team.id}`)])) }); });
composer.callbackQuery(/^admin:scheduleb:(t\d+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await admin(ctx)) || !ctx.session.adminTeamId) return; const data = await readTournament(ctx); const id = `m${data.nextMatch++}`; const match: Match = { id, teamAId: ctx.session.adminTeamId, teamBId: ctx.match?.[1] ?? "", status: "SCHEDULED", scoreA: 0, scoreB: 0 }; data.matches[id] = match; data.matchIds.push(id); data.teams[match.teamAId].matchIds.push(id); data.teams[match.teamBId].matchIds.push(id); ctx.session.adminMatchId = id; ctx.session.flow = "admin_link"; log(data, actor(ctx), "scheduled match", id); await writeTournament(ctx, data); await ctx.reply("Enter the match link, or send - to add it later.", { reply_markup: input }); });
composer.callbackQuery("admin:matches", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await admin(ctx))) return; const data = await readTournament(ctx); if (!data.matchIds.length) return void await ctx.reply("No scheduled matches."); await ctx.reply("Scheduled matches:", { reply_markup: inlineKeyboard(data.matchIds.map((id) => [inlineButton(id, `admin:match:${id}`)])) }); });
composer.callbackQuery(/^admin:match:(m\d+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await admin(ctx))) return; const id = ctx.match?.[1] ?? ""; ctx.session.adminMatchId = id; await ctx.reply("Manage this match.", { reply_markup: inlineKeyboard([[inlineButton("Set link", `admin:link:${id}`), inlineButton("Start live", `admin:start:${id}`)], [inlineButton("Stop live", `admin:stop:${id}`), inlineButton("Update score", `admin:score:${id}`)]] ) }); });
composer.callbackQuery(/^admin:(link|start|stop|score):(m\d+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await admin(ctx))) return; const action = ctx.match?.[1]; const id = ctx.match?.[2] ?? ""; const data = await readTournament(ctx); const match = data.matches[id]; if (!match) return void await ctx.reply("That match is no longer available."); ctx.session.adminMatchId = id; if (action === "start") { match.status = "LIVE"; data.teams[match.teamAId].status = "PLAYING"; data.teams[match.teamBId].status = "PLAYING"; log(data, actor(ctx), "started live match", id); await writeTournament(ctx, data); return void await ctx.reply("Live tracking started."); } if (action === "stop") { match.status = "FINISHED"; data.teams[match.teamAId].status = "FINISHED"; data.teams[match.teamBId].status = "FINISHED"; log(data, actor(ctx), "stopped live match", id); await writeTournament(ctx, data); return void await ctx.reply("Match marked finished."); } ctx.session.flow = action === "link" ? "admin_link" : "admin_score"; await ctx.reply(action === "link" ? "Enter the match link." : "Enter the score as: 2-1", { reply_markup: input }); });
composer.on("message:text", async (ctx, next) => { const flow = ctx.session.flow; if (!flow?.startsWith("admin_")) return next(); if (!(await admin(ctx))) return; const data = await readTournament(ctx); if (flow === "admin_reject") { const team = data.teams[ctx.session.adminTeamId ?? ""]; if (!team) return void await ctx.reply("That roster is no longer available."); team.status = "REJECTED"; log(data, actor(ctx), `rejected roster: ${ctx.message.text.trim().slice(0, 160)}`, team.id); await writeTournament(ctx, data); ctx.session.flow = undefined; await notify(ctx, team, "Your roster was rejected. Open the admin message for the reason."); return void await ctx.reply("Roster rejected and the reason was logged."); } if (flow === "admin_edit_player") { const team = data.teams[ctx.session.adminTeamId ?? ""]; const index = ctx.session.editIndex; const parts = ctx.message.text.split("|").map((part) => part.trim()); if (!team || index === undefined || !parts[0] || !parts[1]) return void await ctx.reply("Send a full name and in-game ID separated by |.", { reply_markup: input }); const player = teamPlayers(data, team)[index]; if (!player) return void await ctx.reply("That player slot is unavailable."); player.fullName = parts[0]; player.inGameId = parts[1]; player.telegramUsername = parts[2] && parts[2] !== "-" ? parts[2] : undefined; team.status = "PENDING"; log(data, actor(ctx), "edited roster", team.id); await writeTournament(ctx, data); ctx.session.flow = undefined; return void await ctx.reply("Roster updated and returned to Pending review."); } const match = data.matches[ctx.session.adminMatchId ?? ""]; if (!match) return void await ctx.reply("That match is no longer available."); if (flow === "admin_link") { const value = ctx.message.text.trim(); if (value !== "-" && !/^https:\/\//i.test(value)) return void await ctx.reply("Enter a full https link, or send - to skip it.", { reply_markup: input }); if (value !== "-") match.link = value; log(data, actor(ctx), "updated match link", match.id); await writeTournament(ctx, data); ctx.session.flow = undefined; return void await ctx.reply("Match link saved."); } const score = /^(\d+)\s*-\s*(\d+)$/.exec(ctx.message.text.trim()); if (!score) return void await ctx.reply("Enter the score as 2-1.", { reply_markup: input }); match.scoreA = Number(score[1]); match.scoreB = Number(score[2]); log(data, actor(ctx), "updated live score", match.id); await writeTournament(ctx, data); ctx.session.flow = undefined; await ctx.reply("Live score updated."); });
export default composer;
