import { Composer } from "grammy";
import type { Ctx } from "../bot.js";
import { adminChatId, inlineButton, inlineKeyboard } from "../toolkit/index.js";
import { createTeam, detectConflicts, log, now, readTournament, teamPlayers, writeTournament, type Player } from "../tournament-store.js";

const composer = new Composer<Ctx>();
const input = { force_reply: true, input_field_placeholder: "Type your answer" } as const;
const state = (ctx: Ctx) => ctx.session;
const label = (index: number) => index < 5 ? `Starter ${index + 1}` : `Substitute ${index - 4}`;
const previewKeys = () => inlineKeyboard([[inlineButton("Submit roster", "register:submit"), inlineButton("Edit roster", "register:edit")], [inlineButton("Cancel", "menu:main")]]);
function contact(ctx: Ctx) { return ctx.from?.username ? `@${ctx.from.username}` : "Telegram captain"; }
function defaultName(ctx: Ctx) { return `${ctx.from?.username ?? "Team"}-${now()}`; }
function formatDraft(name: string, players: Player[]) { return [`Team: ${name}`, "", ...players.map((player, index) => `${label(index)}: ${player.fullName} · ${player.inGameId}${player.telegramUsername ? ` · ${player.telegramUsername}` : ""}`)].join("\n"); }
function reset(ctx: Ctx) { state(ctx).flow = undefined; state(ctx).draft = undefined; state(ctx).editIndex = undefined; }
async function showPreview(ctx: Ctx) { const draft = state(ctx).draft; if (!draft || draft.players.length !== 7) return; state(ctx).flow = "review"; await ctx.reply(`Review your roster:\n\n${formatDraft(draft.name, draft.players)}`, { reply_markup: previewKeys() }); }
async function notifyConflicts(ctx: Ctx, ids: string[]) { const admin = adminChatId(ctx as never); if (!admin) return; for (const conflictId of ids) { try { await ctx.api.sendMessage(admin, `Roster conflict detected. Open the admin panel to resolve conflict ${conflictId}.`, { reply_markup: inlineKeyboard([[inlineButton("Resolve conflict", `admin:conflict:${conflictId}`)]]) }); } catch { /* A blocked admin must not lose the conflict record. */ } } }
composer.callbackQuery("register:start", async (ctx) => { await ctx.answerCallbackQuery(); reset(ctx); state(ctx).flow = "team_name"; state(ctx).draft = { name: "", players: [] }; await ctx.reply("Enter your team name. Send - to use your Telegram name.", { reply_markup: input }); });
composer.callbackQuery("register:edit", async (ctx) => { await ctx.answerCallbackQuery(); const draft = state(ctx).draft; if (!draft || state(ctx).flow !== "review") return void await ctx.reply("Open a roster review before editing."); await ctx.reply("Choose a player to edit.", { reply_markup: inlineKeyboard(draft.players.map((_, index) => [inlineButton(label(index), `register:edit:${index}`)]).concat([[inlineButton("Back to review", "register:review")]])) }); });
composer.callbackQuery(/^register:edit:(\d+)$/, async (ctx) => { await ctx.answerCallbackQuery(); const index = Number(ctx.match?.[1]); const draft = state(ctx).draft; if (!draft || state(ctx).flow !== "review" || !draft.players[index]) return void await ctx.reply("That roster slot is unavailable."); state(ctx).editIndex = index; state(ctx).flow = "edit_name"; await ctx.reply(`Enter the full name for ${label(index)}.`, { reply_markup: input }); });
composer.callbackQuery("register:review", async (ctx) => { await ctx.answerCallbackQuery(); await showPreview(ctx); });
composer.callbackQuery("register:submit", async (ctx) => { await ctx.answerCallbackQuery(); const draft = state(ctx).draft; if (!draft || state(ctx).flow !== "review" || draft.players.length !== 7) return void await ctx.reply("Finish all seven players before submitting."); const ids = draft.players.map((player) => player.inGameId.trim().toLowerCase()); if (ids.some((id) => !id) || new Set(ids).size !== 7) return void await ctx.reply("Each player needs a unique in-game ID. Edit the roster and try again."); const data = await readTournament(ctx); const captainId = String(ctx.from?.id ?? ctx.chat?.id ?? ""); data.users[captainId] = { role: adminChatId(ctx as never) === captainId ? "admin" : "captain" }; const team = createTeam(data, draft.name, captainId, contact(ctx), draft.players); const conflicts = detectConflicts(data, team); log(data, captainId, "submitted roster", team.id); await writeTournament(ctx, data); reset(ctx); await notifyConflicts(ctx, conflicts.map((conflict) => conflict.id)); const message = conflicts.length ? `Your roster is submitted and marked Conflicted. An admin will resolve the duplicate ID.` : "Your roster is submitted and pending approval."; await ctx.reply(message, { reply_markup: inlineKeyboard([[inlineButton("View matches", "matches:show"), inlineButton("Edit team", "edit:team")]]) }); });
composer.on("message:text", async (ctx, next) => { const draft = state(ctx).draft; const value = ctx.message.text.trim(); const flow = state(ctx).flow; if (!flow || !draft) return next(); if (flow === "team_name") { draft.name = value && value !== "-" ? value.slice(0, 80) : defaultName(ctx); state(ctx).flow = "player_name"; await ctx.reply(`Enter the full name for ${label(0)}.`, { reply_markup: input }); return; } const editing = flow.startsWith("edit_"); const index = editing ? state(ctx).editIndex : (flow === "player_name" ? draft.players.length : draft.players.length - 1); if (index === undefined || index < 0) return next(); if (flow === "player_name" || flow === "edit_name") { if (!value) return void await ctx.reply("A full name is required. Try again.", { reply_markup: input }); const player = draft.players[index] ?? { fullName: "", inGameId: "", isSubstitute: index >= 5 }; player.fullName = value.slice(0, 80); draft.players[index] = player; state(ctx).flow = flow === "edit_name" ? "edit_id" : "player_id"; await ctx.reply(`Enter the in-game ID for ${label(index)}.`, { reply_markup: input }); return; } const player = draft.players[index]; if (!player) return void await ctx.reply("That player slot is unavailable."); if (flow === "player_id" || flow === "edit_id") { const duplicate = draft.players.some((candidate, position) => position !== index && candidate.inGameId.trim().toLowerCase() === value.toLowerCase()); if (!value || duplicate) return void await ctx.reply("That in-game ID is missing or already used in this roster. Enter a different ID.", { reply_markup: input }); player.inGameId = value.slice(0, 80); state(ctx).flow = flow === "edit_id" ? "edit_username" : "player_username"; await ctx.reply(`Enter the Telegram username for ${label(index)}, or send - to skip it.`, { reply_markup: input }); return; } if (flow === "player_username" || flow === "edit_username") { player.telegramUsername = value && value !== "-" ? (value.startsWith("@") ? value : `@${value}`).slice(0, 80) : undefined; if (flow === "edit_username") { state(ctx).editIndex = undefined; await showPreview(ctx); return; } if (draft.players.length === 7) { await showPreview(ctx); return; } state(ctx).flow = "player_name"; await ctx.reply(`Enter the full name for ${label(draft.players.length)}.`, { reply_markup: input }); return; } return next(); });
export default composer;
